name: CtrTab
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bleach==6.2.0
      - category-encoders==2.8.1
      - click==7.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - copulas==0.9.2
      - cycler==0.12.1
      - datasets==3.5.1
      - dill==0.3.8
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - faker==37.1.0
      - fonttools==4.57.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - huggingface-hub==0.30.2
      - icecream==2.1.4
      - imbalanced-learn==0.13.0
      - joblib==1.5.0
      - kaggle==1.7.4.2
      - matplotlib==3.10.1
      - ml-collections==1.1.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - nvidia-nccl-cu12==2.26.5
      - openpyxl==3.1.5
      - packaging==25.0
      - patsy==1.0.1
      - peft==0.9.0
      - plotly==5.24.1
      - ply==3.11
      - prdc==0.2
      - progressbar2==4.5.0
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-graphviz==0.20.3
      - python-slugify==8.0.4
      - python-utils==3.9.1
      - pytz==2025.2
      - quantiphy==2.20
      - rdt==1.16.0
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sdmetrics==0.11.1
      - setuptools-scm==8.3.1
      - sklearn-compat==0.1.3
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - tomli-w==1.2.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - webencodings==0.5.1
      - xgboost==3.0.0
      - xlrd==2.0.1
      - xxhash==3.5.0
      - yarl==1.20.0
      - zero==0.9.2

